LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES:= args.c
LOCAL_SHARED_LIBRARIES += libc libcutils
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE := args
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES:= args-env.c
LOCAL_SHARED_LIBRARIES += libc libcutils
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE := args-env
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
include $(BUILD_EXECUTABLE)
